analytics/http_api.rst, analytics/index.yaml, analytics/tracker_snippet.rst
Removed API version parameter from analytics HTTP API
=> Fixed deprecation version

sdk/Piwik_PRO_SDK_for_Android.md
Native speaker incorrectly changed sense of thsentence; typo
=> Small text corrections. 

conf.py, index.rst, platform/index.rst, platform/public_api/access_control/access_control_api.rst, platform/public_api/access_control/index.json, platform/public_api/apps/apps_api.rst, platform/public_api/apps/index.json, platform/public_api/users/index.json, platform/public_api/users/users_api.rst, platform/public_api_guide.md
* public oauth guide introduction
* public docs for: Apps, Users, Access Control
=> feature/PPCDEV-7517 public oauth guide introduction, public docs for: Apps, Users, Access Control

platform/public_api/apps/index.json
* gdpr manual mode
* cookie expiration period
* small fixes of existing docs
=> PPCDEV-7059 Apps api docs

Makefile, conf.py, make.bat
Looks like we didn't propagate these changes to future versions. Can you confirm that all configs should be updated?
=> [INTERNAL] Changed texts on title and copyright

platform/authorized_api/apps/index.json
Cleaned up changes from https://github.com/PiwikPRO/PPMS-PublicDocs/pull/71 PR.
Includes rebase and some conflicts resolution so there may be errors.
=> Added attributes (rebase)

audience_manager/form-tracker.rst
Changed inslallation tag to encompass form configuration and new options
Added description about useLabel option
Added description of trackingType option
=> PPROF-1257 Updated Form Tracker API

platform/authorized_api/apps/index.json, platform/authorized_api_guide.md
=> PPCDEV-8658: increase default pagination limit in apps

audience_manager/api.rst, audience_manager/authorized_api/definitions/export_attribute.yaml
Added explanation of field_type values
=> PPROF-1315 Explanation of filed_type

audience_manager/api.rst
Update user attributes action description now uses a lot less notes
Preview:
https://developers.piwik.pro/en/feature-pprof-1144-shortening-description/audience_manager/api.html#update-user-attributes
=> PPROF-1144 Shorter description

_static/js/custom.js, conf.py, requirements.local.txt
Can be tested here:
5.5 rebuild:
https://developers.piwik.pro/en/5.5-rebuild/analytics/http_api.html
5.5 with fix:
https://developers.piwik.pro/en/5.5-css-fix/analytics/http_api.html
=> PPTECHDOC-54 Fixed styes loading sequence

requirements.txt
Can be tested here: https://developers.piwik.pro/en/bugfix-vulnarable-package-update/audience_manager/public_api/audience_manager_api.html
=> PPTECHDOC-47 Updated vulnerable package

analytics/index.yaml
Change formatting of ec_items parameter
=> PROD-1360 Fixed wrong format of Piwik E-Commerce HTTP API parameter

platform/authorized_api_guide.md
Context:
https://clearcodehq.atlassian.net/browse/PROD-1406
It's a hotfix for our current version of documentation. 
Complete fix for this issue will be a part of another task:
https://clearcodehq.atlassian.net/browse/PPCDEV-10657
=> PROD-1406 Fix documentation links

audience_manager/api.rst
@TomaszUrugOlszewski Please chceck if description matches behavior of the backend.
You can generate docs in docker (see readme file)
=> PPROF-1680 Added list handling in JS API

audience_manager/authorized_api/definitions/audience.yaml, audience_manager/authorized_api/definitions/audience_count.yaml, audience_manager/authorized_api/index.yaml
- Update public docs to support audience history count
=> PPROF-1531 add audience count history to protected AM api

audience_manager/authorized_api/definitions/profile_details.yaml, audience_manager/authorized_api/definitions/profile_list.yaml, audience_manager/authorized_api/index.yaml, audience_manager/authorized_api/paths/profiles_get.yaml
Docs for AM API to get profiles by ID
=> PPROF-1601 AM API to get profiles

audience_manager/authorized_api/definitions/profile_details.yaml
Add new object generic and additional keys to goal example to profile_details
=> PPROF-1713 Add generic object and new goal keys to profile

platform/authorized_api/apps/public_v2.yaml
=> PPCDEV-10865 Paginate apps via backend and add updatedAt field to a list

custom_reports/http_api/definitions/query_request.yaml, custom_reports/http_api/definitions/raw_data_request.yaml
Add relative_date field to new analytics public API.
=> PPNA-1845 add relative date property to analytics API

consent_manager/js_api/commands.rst, consent_manager/js_api/introduction.rst
Add description of new openConsentForm command
=> TM-5692: Consent form cannot be opened on SPA

analytics/http_api.rst, analytics/reporting_api.rst
=> PPTECHDOC-66 Added deprecation warning for reportning API

custom_reports/object_management_api/definitions/custom_dimension.yaml, custom_reports/object_management_api/definitions/custom_dimension_details.yaml, custom_reports/object_management_api/definitions/custom_dimension_list.yaml, custom_reports/object_management_api/definitions/custom_dimension_slot.yaml, custom_reports/object_management_api/definitions/custom_dimension_slots.yaml, custom_reports/object_management_api/index.yaml, custom_reports/object_management_api/paths/custom_dimensions.yaml, custom_reports/object_management_api/paths/custom_dimensions_detail.yaml, custom_reports/object_management_api/paths/custom_dimensions_slots.yaml
I think it's the best to keep Goals and CD API in same branch
=> PPNA-2623 - Docs for Custom Dimensions API

audience_manager/authorized_api/definitions/export_attribute.yaml, audience_manager/authorized_api/definitions/export_data.yaml
@RomanSek @JacekClearcode Please build this branch, I'm not sure that all formatting looks good.
=> PPNA-2811 Updated AM docs

tracker/js_tracking_api.rst, tracker/tracker_object.rst
TBD: release version
Preview:
https://developers.piwik.pro/en/feature-pptt-922-new-ecommerce-methods/tracker/js_tracking_api.html#ecommerce-tracking
https://developers.piwik.pro/en/feature-pptt-922-new-ecommerce-methods/tracker/tracker_object.html#ecommerce-tracking
=> PPTT-922 New ecommerce methods

analytics/js_tracking_api.rst, analytics/tracker_object.rst
Preview: https://developers.piwik.pro/en/bugfix-pptt-1015-tracker-documentation-fix/analytics/js_tracking_api.html
=> PPTT-1015 Tracker documentation fix

analytics/js_tracking_api.rst
Preview: https://developers.piwik.pro/en/bugfix-pptt-1015-fixed-formatting/analytics/js_tracking_api.html#gathering-navigation-timing-page-performance-metrics
=> PPTT-1015 Fixed message formatting

analytics/tracker_object.rst
Preview: https://developers.piwik.pro/en/bugfix-pptt-1015-typo/analytics/tracker_object.html#resetUserId
=> PPTT-1015 Typo

tracker/tracker_object.rst
Preview:
https://developers.piwik.pro/en/feature-pptt-984-custom-cross-domain-links/tracker/tracker_object.html#customCrossDomainLinkDecorator
=> PPTT-984 Added cross domain link customization methods

consent_manager/examples/api_full_example.html
Move setInitialConsents to init
=> TM-6400: Custom Consent Form - send initial stats on open

tag_manager/authorized_api/src/changelog/schema/changelog_attributes.json, tag_manager/authorized_api/src/changelog/schema/list/changelog_list_response_schema.json
- updates Tag Manager authorized api documentation
=> TM-6613: PPMS 15.0.1 - Release

tag_manager/authorized_api/src/changelog/schema/changelog_attributes.json, tag_manager/authorized_api/src/changelog/schema/list/changelog_list_response_schema.json
- updates Tag Manager authorized api documentation
=> TM-6613: PPMS 15.0.1 - Release (#503)

tracker/js_tracking_api.rst, tracker/tracker_object.rst
=> PPTT-1025 Changed default value used by enableHeartBeatTimer method

tracker/js_tracking_api.rst, tracker/tracker_object.rst
DO NOT MERGE TO 15.1 (changes for next version)
Preview:
https://developers.piwik.pro/en/feature-pptt-1362-added-ping-method/tracker/js_tracking_api.html#send-ping-request-on-demand
https://developers.piwik.pro/en/feature-pptt-1362-added-ping-method/tracker/tracker_object.html#ping
=> PPTT-1362 Added ping method

consent_manager/js_api/commands.rst
Provide documentation for new commands used for tracking Custom Forms
=> TM-7311: Add docs for new Custom Form tracking commands

tracker/js_tracking_api.rst, tracker/tracker_object.rst
Preview:
https://developers.piwik.pro/en/feature-pptt-1966-increase-hb-interval/tracker/js_tracking_api.html#measuring-user-time-spent-on-web-page
https://developers.piwik.pro/en/feature-pptt-1966-increase-hb-interval/tracker/tracker_object.html#enableHeartBeatTimer
=> PPTT-1966 Described incresing heartbeat interval mechanism

tag_manager/content_security_policy.rst
Add instruction related to Data Subject Request
=> TM-7457: Add instruction related to Data Subject Request

tag_manager/content_security_policy.rst, tag_manager/index.rst
- move content from pdf with documentation and adjust to newest snippets
=> TM-7061: Provide CSP documentation

consent_manager/custom_consent_form/enable-custom-consent-form.rst, consent_manager/custom_consent_form/example.rst
Fix a broken link to JavaScript API
=> TM-7541: Fix a broken link to JavaScript API

tracker/tracker_object.rst
Preview:
https://developers.piwik.pro/en/feature-pptt-1845-added-enable-cookies-method/tracker/tracker_object.html#tracking-cookies-management
=> PPTT-1845 Added enableCookies method

tracker/tracker_object.rst
Preview:
https://developers.piwik.pro/en/feature-pptt-1975-fixed-param-type-and-added-missing-function/tracker/tracker_object.html#trackEvent
https://developers.piwik.pro/en/feature-pptt-1975-fixed-param-type-and-added-missing-function/tracker/tracker_object.html#trackEvent
=> PPTT-1975 Fixed param type and added missing function

tracker/js_tracking_api.rst
Preview: https://developers.piwik.pro/en/feature-fixed-number-list-format/tracker/js_tracking_api.html#installing-tracking-code-via-tag-manager
=> Fixed number list format

tracker/tracker_debugger_api.yaml
Preview: https://developers.piwik.pro/en/pptt-2316-additional-debug-endpoint-parameters/tracker/tracker_debugger_api.html
=> PPTT-2316 Added `page_url` and `event_type` parameters for `public_processor_storage_api_v1`

platform/authorized_api/apps/public_v2.yaml
sorry for that :sadpanda: we need to have it also in `15.3`, `15.4`, `15.5` and `15.6`
=> PPCDEV-13495 remove deprecation in apps

custom_reports/object_management_api/definitions/annotation.yaml, custom_reports/object_management_api/definitions/annotation_system.yaml, custom_reports/object_management_api/definitions/annotation_user.yaml, custom_reports/object_management_api/definitions/annotation_user_detail.yaml, custom_reports/object_management_api/index.yaml, custom_reports/object_management_api/paths/annotation_system.yaml, custom_reports/object_management_api/paths/annotation_user.yaml, custom_reports/object_management_api/paths/annotation_user_detail.yaml
Connected with https://github.com/PiwikPRO/PPMS-Analytics-Reporting/pull/1804
=> PPNA-3887 Analytics annotations

tracker/js_tracking_api.rst, tracker/tracker_object.rst
DO NOT MERGE (changes for PPAS version using new tracker)
Preview:
https://developers.piwik.pro/en/feature-pptt-1367-add-search-multi-category/tracker/js_tracking_api.html#tracking-internal-searches
https://developers.piwik.pro/en/feature-pptt-1367-add-search-multi-category/tracker/tracker_object.html#trackSiteSearch
=> PPTT-1367 Added search multi category option

data_collection/other_integrations/index.rst, data_collection/web/guides.rst, data_collection/web/javascript_tracking_client/api.rst, data_collection/web/javascript_tracking_client/installation.rst
=> PPTT-2696 added custom events section

data_collection/web/guides.rst, data_collection/web/javascript_tracking_client/api.rst, data_collection/web/javascript_tracking_client/index.rst, data_collection/web/javascript_tracking_client/reserved_names.rst
=> PPTT-2696 added ecommerce guide and labels to ecommerce functions

data_collection/web/javascript_tracking_client/api.rst
Preview: https://developers.piwik.pro/en/feature-pptt-2605-unique-js-error/data_collection/web/javascript_tracking_client/api.html#enableJSErrorTracking
=> PPTT-2605 Unique JS errors

data_collection/web/javascript_tracking_client/api.rst
[Preview](https://developers.piwik.pro/en/feature-jtc-code-tabs/data_collection/web/javascript_tracking_client/api.html)
=> Added tabs to JavaScript tracing client

data_collection/web/guides.rst
[Preview](https://developers.piwik.pro/en/pptt-2753-user-id-guide/data_collection/web/guides.html)
=> PPTT-2753 Added a `User ID` guide

tag_manager/authorized_api/src/variables.yaml
- provide collapsable variables list
=> TM-5981 Add builtin variables list

tag_manager/authorized_api/src/changelog/schema/changelog_content_attributes.json, tag_manager/authorized_api/src/tags/schema/create/request/video_html5_create.json, tag_manager/authorized_api/src/tags/schema/create/request/video_youtube_create.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_request_schema.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_response_schema.json, tag_manager/authorized_api/src/tags/schema/edit/request/video_html5_edit.json, tag_manager/authorized_api/src/tags/schema/edit/request/video_youtube_edit.json, tag_manager/authorized_api/src/tags/schema/edit/tags_edit_request_schema.json, tag_manager/authorized_api/src/tags/schema/get/response/video_html5_get.json, tag_manager/authorized_api/src/tags/schema/get/response/video_youtube_get.json, tag_manager/authorized_api/src/tags/schema/get/tags_get_response_schema.json, tag_manager/authorized_api/src/tags/schema/tag_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/piwik_base_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/piwik_custom_dimension_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/video_html5_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/video_youtube_attributes.json, tag_manager/authorized_api/src/variables.yaml
- add documentation for video tracking
- modify documentation for custom dimension limit
=> TM-8725 Update TM API docs

platform/authorized_api/apps/public_v2.yaml
Could you please merge it up to 15.6?
=> adding an app with forced id

data_collection/api/tracker_debugger_api.yaml, data_collection/api/tracking_api.yaml
Changes in debugger API have been copied from api docs:
https://piwikpro.atlassian.net/wiki/spaces/PPTP/pages/85949317734/Differences+in+visitors+recognition+between+regular+tracking+and+log+replay.?focusedCommentId=85949579323#comment-85949579323
=> PPTT-3037 renamed rand parameter to r, updated PSA debugger docs

data_collection/api/http_api.rst, data_collection/api/tracker_debugger_api.rst, data_collection/api/tracker_debugger_api.yaml, data_collection/web/guides.rst, data_collection/web/javascript_tracking_client/api.rst, glossary.rst, index.rst, platform/authorized_api/tracker_settings/public_v2.yaml, platform/authorized_api/tracker_settings/tracker_settings_api.rst, tag_manager/content_security_policy.rst, tracker/tracker_debugger_api.rst
[Preview](https://developers.piwik.pro/en/feature-pptt-3045-replace-cpp-shortcut/search.html?q=Collecting+%26+Processing+Pipeline&check_keywords=yes&area=default)
=> PPTT-3045 Replaced all CPP shortsuts with full term and links to glossary

tag_manager/authorized_api/src/changelog/schema/changelog_content_attributes.json, tag_manager/authorized_api/src/tags/schema/create/request/heatmaps_create.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_request_schema.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_response_schema.json, tag_manager/authorized_api/src/tags/schema/edit/request/heatmaps_edit.json, tag_manager/authorized_api/src/tags/schema/edit/tags_edit_request_schema.json, tag_manager/authorized_api/src/tags/schema/get/response/heatmaps_get.json, tag_manager/authorized_api/src/tags/schema/get/tags_get_response_schema.json, tag_manager/authorized_api/src/tags/schema/tag_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/heatmaps_attributes.json
- add heatmaps tag documentation
=> TM-9047 Update TM API docs

data_collection/web/javascript_tracking_client/api.rst
[Preview](https://developers.piwik.pro/en/feature-pptt-3137-added-setsessionidstrictprivacymode/data_collection/web/javascript_tracking_client/api.html#setSessionIdStrictPrivacyMode)
=> PPTT-3137 Added setSessionIdStrictPrivacyMode description

data_collection/web/javascript_tracking_client/api.rst
Bug was reported [here](https://piwikpro.slack.com/archives/C8DJGLVRU/p1640183821001700).
=> Fixed trackGoal examples

platform/authorized_api/apps/public_v2.yaml
apps API docs for release 16.14
=> PPPCDEV-14845 apps api docs for release 16.14

tag_manager/authorized_api/src/common/api/common_error_responses.json, tag_manager/authorized_api/src/common/example/error/common_service_unavailable_response_example.json, tag_manager/authorized_api/src/tags.yaml, tag_manager/authorized_api/src/triggers.yaml, tag_manager/authorized_api/src/variables.yaml, tag_manager/authorized_api/src/versions.yaml
- add documentation for TagManager maintenance mode
=> TM-9485 Add documentation for TagManager maintenance mode

tag_manager/authorized_api/src/common/api/common_error_responses.json, tag_manager/authorized_api/src/common/example/error/common_service_unavailable_response_example.json, tag_manager/authorized_api/src/tags.yaml, tag_manager/authorized_api/src/triggers.yaml, tag_manager/authorized_api/src/variables.yaml, tag_manager/authorized_api/src/versions.yaml
- add documentation for TagManager maintenance mode
=> TM-9630 Add documentation for TagManager maintenance mode

data_collection/mobile/Piwik_PRO_SDK_for_React_Native.md
the npm package name was incorrect in the installation instructions.
=> docs: update installation instructions

platform/authorized_api/container_settings/src/example/app_container_settings_list_response_example.json, platform/authorized_api/container_settings/src/example/organization_container_settings_list_response_example.json, platform/authorized_api/container_settings/src/schema/common_request_parameters.json, platform/authorized_api/container_settings/src/schema/request/app_container_setting_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/request/app_container_settings_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/request/organization_container_setting_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/request/organization_container_settings_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/response/app_container_setting_response_schema.json, platform/authorized_api/container_settings/src/schema/response/app_container_settings_list_response_schema.json, platform/authorized_api/container_settings/src/schema/response/organization_container_setting_response_schema.json, platform/authorized_api/container_settings/src/schema/response/organization_container_settings_list_response_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_app_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_app_request_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_app_response_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_organization_edit_request_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_organization_request_schema.json, platform/authorized_api/container_settings/src/schema/settings/spa_tracking/spa_tracking_organization_response_schema.json
- add documentation for Container Settings SPA toggle
=> TM-9702 SPA toggle documentation for Container Settings

tag_manager/authorized_api/src/tags/schema/tag_types.json
- update tag manager public docs
=> TM-10037 Update Tag Manager Api Docs 16.20

platform/authorized_api/users/public_v2.yaml
=> PPCDEV-15456 users API docs

custom_reports/http_api/definitions/query_request.yaml
=> PPNA-5271 Add sampling option to analytics http api

custom_reports/http_api/definitions/query_request.yaml
Reverts PiwikPRO/PPMS-PublicDocs#955
=> Revert "PPNA-5271 Add sampling option to analytics http api"

data_collection/web/frameworks/Piwik_PRO_Library_for_Angular.md
Updated docs for the Angular library to match the README in [its repo](https://github.com/PiwikPRO/ngx-piwik-pro):
- setup with nonce (CSP)
- info about using the data layer
This can be merged independently of any version - changes apply to current version 16.35 and older versions too, that's why I chose `master` as the base. There was also no 16.36 branch yet, but feel free to merge with the next release.
=> PPI-456 Update Angular library docs

tag_manager/content_security_policy.rst
Update CSP guidelines to allow for container deployment without domain whitelist
=> TM-11856 Update CSP guidelines to allow for container deployment without domain whitelist

data_collection/web/javascript_tracking_client/api.rst
[Preview](https://developers.piwik.pro/en/feature-pptt-3929-ecommerce-v2/data_collection/web/javascript_tracking_client/api.html#e-commerce-v2)
=> PPTT-3929 Added Ecommerce v2 docs

data_collection/web/guides.rst, data_collection/web/javascript_tracking_client/api.rst
Preview:
* [Guide](https://developers.piwik.pro/en/feature-pptt-4021-updated-guides-to-ecommerce-v2/data_collection/web/guides.html#e-commerce-v2)
* [API](https://developers.piwik.pro/en/feature-pptt-4021-updated-guides-to-ecommerce-v2/data_collection/web/javascript_tracking_client/api.html#e-commerce-v2)
=> PPTT-4021 Updated guides to ecommerce v2

data_collection/web/javascript_tracking_client/api.rst
[Preview](https://developers.piwik.pro/en/feature-pptt-4066-added-setiptracking/data_collection/web/javascript_tracking_client/api.html#setIpTracking)
=> PPTT-4066 Added setIpTracking method

data_collection/web/guides.rst, data_collection/web/javascript_tracking_client/api.rst
Preview:
* [API](https://developers.piwik.pro/en/feature-pptt-4041-ecommerce-fixes/data_collection/web/javascript_tracking_client/api.html#e-commerce-v2)
* [Guides](https://developers.piwik.pro/en/feature-pptt-4041-ecommerce-fixes/data_collection/web/guides.html#e-commerce)
=> PPTT-4041 Various ecommerce fixes

_static/css/custom_1684133308817.css, _static/js/custom1653024076375.js, _templates/layout.html, audience_manager/index.rst, conf.py, customer_data_platform/index.rst, customer_data_platform/public_api/components.yaml, customer_data_platform/public_api/customer_data_platform_profiles_api.yaml, customer_data_platform/public_api/public_api.rst, data_collection/mobile/Piwik_PRO_SDK_for_Android.md, data_collection/mobile/Piwik_PRO_SDK_for_Flutter.md, data_collection/mobile/Piwik_PRO_SDK_for_React_Native.md, data_collection/mobile/Piwik_PRO_SDK_for_iOS.md, index.rst
Changes summary:
Added CDP to main menu:
Deprecation note in AM:
CDP docs main page:
Warning on AM deprecation in each SDK:
=> PPCDP-842 Initial documentation of CDP on developers.piwik.pro

data_collection/web/javascript_tracking_client/api.rst
Ustawiam na mastera, bo nie widzę jeszcze 17.4
=> Improving setCustomRequestProcessing description (PPPSYS-41263)

platform/authorized_api/tracker_settings/public_v2.yaml
PPTT-4088 Product custom dimensions
=> PPTT-4088 Product custom dimensions

tag_manager/authorized_api/src/tags/schema/create/request/ecommerce_add_to_cart_create.json, tag_manager/authorized_api/src/tags/schema/create/request/ecommerce_order_create.json, tag_manager/authorized_api/src/tags/schema/create/request/ecommerce_product_detail_view_create.json, tag_manager/authorized_api/src/tags/schema/create/request/ecommerce_remove_from_cart_create.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_request_schema.json, tag_manager/authorized_api/src/tags/schema/create/tags_create_response_schema.json, tag_manager/authorized_api/src/tags/schema/edit/request/ecommerce_add_to_cart_edit.json, tag_manager/authorized_api/src/tags/schema/edit/request/ecommerce_order_edit.json, tag_manager/authorized_api/src/tags/schema/edit/request/ecommerce_product_detail_view_edit.json, tag_manager/authorized_api/src/tags/schema/edit/request/ecommerce_remove_from_cart_edit.json, tag_manager/authorized_api/src/tags/schema/edit/tags_edit_request_schema.json, tag_manager/authorized_api/src/tags/schema/get/response/ecommerce_add_to_cart_get.json, tag_manager/authorized_api/src/tags/schema/get/response/ecommerce_order_get.json, tag_manager/authorized_api/src/tags/schema/get/response/ecommerce_product_detail_view_get.json, tag_manager/authorized_api/src/tags/schema/get/response/ecommerce_remove_from_cart_get.json, tag_manager/authorized_api/src/tags/schema/get/tags_get_response_schema.json, tag_manager/authorized_api/src/tags/schema/tag_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/ecommerce/ecommerce_add_to_cart_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/ecommerce/ecommerce_common_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/ecommerce/ecommerce_order_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/ecommerce/ecommerce_product_detail_view_attributes.json, tag_manager/authorized_api/src/tags/schema/tag_templates/ecommerce/ecommerce_remove_from_cart_attributes.json
- added documentation for new ecommerce tracking tag templates
=> TM-12698 Update Tag Manager API docs - Release 17.8.0

customer_data_platform/authorized_api/customer_data_platform_audiences_api.yaml
This PR should be to 18.7 - waiting for the branch
=> PPCDP-1567 Increased membership duration in CDP Audiences

tag_manager/authorized_api/src/operations/example/get/operations_get_response_example.json, tag_manager/authorized_api/src/tags/example/copy/tags_copy_request_example.json, tag_manager/authorized_api/src/tags/schema/tag_types.json, tag_manager/authorized_api/src/triggers/example/copy/triggers_copy_request_example.json, tag_manager/authorized_api/src/triggers/example/copy/triggers_copy_response_example.json, tag_manager/authorized_api/src/triggers/schema/create/request/capturing_click_schema.json, tag_manager/authorized_api/src/triggers/schema/create/triggers_create_request_schema.json, tag_manager/authorized_api/src/triggers/schema/create/triggers_create_response_schema.json, tag_manager/authorized_api/src/triggers/schema/edit/request/capturing_click_schema.json, tag_manager/authorized_api/src/triggers/schema/edit/triggers_edit_request_schema.json, tag_manager/authorized_api/src/triggers/schema/get/response/capturing_click_schema.json, tag_manager/authorized_api/src/triggers/schema/get/triggers_get_response_schema.json, tag_manager/authorized_api/src/triggers/schema/trigger_attributes.json, tag_manager/authorized_api/src/triggers/schema/trigger_type_attributes.json, tag_manager/authorized_api/src/variables/example/copy/variables_copy_request_example.json, tag_manager/authorized_api/src/variables/example/copy/variables_copy_response_example.json
- added documentation for new trigger type: capturing click
=> TM-13283 Update Tag Manager API docs - Release 18.7.0

_templates/layout.html
Need to update docs. CDP is not new anymore.
Task: https://piwikpro.atlassian.net/browse/PPCDP-1696
=> PPCDP-1696 removed new from cdp in nav bar

data_collection/web/frameworks/Piwik_PRO_Library_for_NextJS.md, data_collection/web/frameworks/Piwik_PRO_Library_for_React.md
[Jira ticket](https://piwikpro.atlassian.net/browse/PPI-1023?atlOrigin=eyJpIjoiNjIzMjM0NmNhOWU1NDNmMDlkNThjMTQzNjg2OWMwMGEiLCJwIjoiaiJ9)
=> backward compatibility for new ecommerce methods in react and next

platform/authorized_api/users/public_v2.yaml
=> Minimal password length changed to 12

custom_reports/http_api/definitions/raw_data_real_time_request.yaml, custom_reports/http_api/index.yaml, custom_reports/http_api/paths/real_time_events.yaml
This PR is to branch containing [copy-pasted documentation of raw events API](https://github.com/PiwikPRO/PPMS-PublicDocs/compare/feature/rtr...PPNA-6416-copy-paste-events-to-rtr?expand=1) - this is to highlight changes in docs.
after accepts I'd change target to `feature/rtr` and merge directly there
=> PPNA-6416 Real-time events API

custom_reports/http_api/definitions/real_time_query_request.yaml, custom_reports/http_api/index.yaml, custom_reports/http_api/paths/real_time_query.yaml
Copy/paste of query API with `date_from/date_to -> lookback_window` change
=> PPNA-6416 Real-time query API

custom_reports/columns__dimension_to_dimension_transformations.rst
added `to_start_of_five_minutes`, `to_start_of_ten_minutes`
=> PPNA-6660 New transformations

conf.py, customer_data_platform/components.yaml, customer_data_platform/index.rst, customer_data_platform/public_api/customer_data_platform_profiles_api.yaml, customer_data_platform/public_api/customer_data_platform_webhooks_api.yaml, customer_data_platform/public_api/index.rst, customer_data_platform/public_api/profiles.rst, customer_data_platform/public_api/webhooks.rst
Descriptions and the overall structure come from internal CDP documentation.
=> PPCDP 2199: CDP: Add data import API docs to Public Docs

data_collection/web/guides.rst
Remove mention of Synchronous container - cloned from https://github.com/PiwikPRO/PPMS-PublicDocs/pull/1165 to appropriate branch.
Caught by @rmastop-pp
=> Remove mention of Synchronous container 

data_collection/web/javascript_tracking_client/api.rst
=> PPSDK-229 mobile app URIs in domains

customer_data_platform/profile_attributes.rst, index.rst
CDP urls are wrong and going to 404
=> PPCDP-2645 changed cdp urls

custom_reports/object_management_api/index.yaml
before:
https://developers.piwik.pro/en/latest/custom_reports/object_management_api/object_management_api.html#tag/Goals/paths/~1api~1analytics~1v1~1manage~1goals~1/get
after:
=> PPNA-7021 Add missing information about default limit
